apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hardware-inventory
resources:
- namespace.yaml
- infraenv.yaml

secretGenerator:
  - name: pull-secret
    options:
      disableNameSuffixHash: true
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=pull-secret.txt
